name: Lint

on:
  push:
    branches:
      - "**"        # run on all branches
  pull_request:
    branches:
      - "**"        # run on all branches

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint
